#!/bin/bash

#ddev-generated

## Description: Run taskfile.dev command inside the web container
## Usage: task [args]
## Example: "task typo3cms build:frontend"
## ExecRaw: true
## HostWorkingDir: true

task "$@"
